spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/fitnessdb
spring.datasource.username=postgres
spring.datasource.password=yash

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true